/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import config.koneksi;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.modelutang;

/**
 *
 * @author attia
 */
public class detailutang extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(detailutang.class.getName());

    /**
     * Creates new form detailutang
     */
   
    
    public detailutang() {
        initComponents();
        this.setLocationRelativeTo(null);
        tableCicilan.setRowHeight(35);
        tableCicilan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        setUkuranFrame15x20();
    }
    
    public detailutang(modelutang mu){
    initComponents();
    this.mu = mu;
    setUkuranFrame15x20();
    setBayarPerbulan();  
    loadHeader(mu);
    loadTableCicilan(mu);
    setLocationRelativeTo(null);
    }
    
    private void setUkuranFrame15x20() {
    int lebar = 567;  // 15 cm
    int tinggi = 756; // 20 cm

    setSize(lebar, tinggi);
    setPreferredSize(new Dimension(lebar, tinggi));
    setResizable(false);
}
private String formatRupiah(int nilai) {
    return String.format("%,d", nilai).replace(',', '.');
}
private modelutang mu;
private void loadHeader(modelutang mu) {
    lblKodeUtang.setText(mu.getKdutang());
    lblNama.setText(mu.getNama());
    lblAlamat.setText(mu.getAlamat());
    lblTelepon.setText(String.valueOf(mu.getTelepon()));
    lblHarga.setText("Rp " + formatRupiah(mu.getHargabrng()));
    lblDP.setText("Rp "+ formatRupiah(mu.getDp()));
}

private void setBayarPerbulan() {
   if (mu == null) return;

    int hargaBarang   = mu.getHargabrng();
    int dp            = mu.getDp();
    int jumlahCicilan = mu.getJumlahcicilan();

    if (jumlahCicilan <= 0) return;

    int bayarPerbulan = (hargaBarang - dp) / jumlahCicilan;

    txtperbulan.setText(
        "Rp " + String.format("%,d", bayarPerbulan)
    );
}

private void loadTableCicilan(modelutang mu) {

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Cicilan Ke");
    model.addColumn("Tanggal Jatuh Tempo");
    model.addColumn("Nominal Bayar");
    model.addColumn("Sisa Hutang");
    model.addColumn("Paraf");

    for (int i = 1; i <= 15; i++) {

        Object[] row = new Object[]{
            null,
            null,
            null,
            null,
            null // Paraf dikosongkan
        };

        model.addRow(row);
    }

    tableCicilan.setModel(model);
}


private void print15x20() {

    PrinterJob job = PrinterJob.getPrinterJob();
    job.setJobName("Detail Utang 15x20");

    PageFormat pf = job.defaultPage();
    Paper paper = new Paper();

    // === UKURAN 15 x 20 CM ===
    double width = 425;   // 15 cm
    double height = 567;  // 20 cm

    paper.setSize(width, height);

    // Margin aman
    paper.setImageableArea(
        20, 20,
        width - 40,
        height - 40
    );

    pf.setPaper(paper);
    pf.setOrientation(PageFormat.PORTRAIT);

    job.setPrintable((graphics, pageFormat, pageIndex) -> {

        if (pageIndex > 0) return Printable.NO_SUCH_PAGE;

        Graphics2D g2d = (Graphics2D) graphics;

        double panelWidth = panelDetailutang.getWidth();
        double panelHeight = panelDetailutang.getHeight();

        double printableWidth = pageFormat.getImageableWidth();
        double printableHeight = pageFormat.getImageableHeight();

        // === SCALE OTOMATIS ===
        double scaleX = printableWidth / panelWidth;
        double scaleY = printableHeight / panelHeight;
        double scale = Math.min(scaleX, scaleY);

        // === CENTER HORIZONTAL ===
        double x = pageFormat.getImageableX()
                + (printableWidth - panelWidth * scale) / 2;

        double y = pageFormat.getImageableY();

        g2d.translate(x, y);
        g2d.scale(scale, scale);

        panelDetailutang.printAll(g2d);

        return Printable.PAGE_EXISTS;

    }, pf);

    if (job.printDialog()) {
        try {
            job.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetailutang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblKodeUtang = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblTelepon = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblDP = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCicilan = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtperbulan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(567, 756));

        panelDetailutang.setBackground(new java.awt.Color(255, 255, 255));
        panelDetailutang.setPreferredSize(new java.awt.Dimension(360, 504));
        panelDetailutang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setText("Kode Transaksi :");
        panelDetailutang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Nama             :");
        panelDetailutang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("Telepon          :");
        panelDetailutang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Alamat           :");
        panelDetailutang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Dp                  :");
        panelDetailutang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Harga Barang :");
        panelDetailutang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        lblKodeUtang.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblKodeUtang.setText("jLabel10");
        panelDetailutang.add(lblKodeUtang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        lblNama.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblNama.setText("jLabel10");
        panelDetailutang.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        lblTelepon.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTelepon.setText("jLabel10");
        panelDetailutang.add(lblTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        lblAlamat.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblAlamat.setText("jLabel10");
        panelDetailutang.add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        lblDP.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblDP.setText("jLabel10");
        panelDetailutang.add(lblDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        lblHarga.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblHarga.setText("jLabel10");
        panelDetailutang.add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        tableCicilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCicilan);

        panelDetailutang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 530, 270));

        jButton3.setText("Kembali");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        panelDetailutang.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jButton4.setText("Print");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        panelDetailutang.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("KARTU ANGSURAN");
        panelDetailutang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        jLabel8.setText("SARI MURNI REJEKI");
        panelDetailutang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        txtperbulan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtperbulan.setText("jLabel10");
        panelDetailutang.add(txtperbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("Bayar Perbulan:");
        panelDetailutang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetailutang, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetailutang, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        print15x20();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new detailutang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblDP;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKodeUtang;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTelepon;
    private javax.swing.JPanel panelDetailutang;
    private javax.swing.JTable tableCicilan;
    private javax.swing.JLabel txtperbulan;
    // End of variables declaration//GEN-END:variables
}
