/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import config.koneksi;
import controller.logtcontroller;
import controller.transaksiservice;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.modelbarang;
import model.modellogt;
import model.modeltd;
import model.modeltransaksi;

/**
 *
 * @author attia
 */
public class logtransaksi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(logtransaksi.class.getName());

    /**
     * Creates new form logtransaksi
     */
    DefaultTableModel model;
    logtcontroller lc = new logtcontroller();

    public logtransaksi() {
        initComponents();
        initTable();
        loadData();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

private void initTable() {
    model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("Kode Transaksi");
    model.addColumn("Tanggal");
    model.addColumn("Nama Pelanggan");
    model.addColumn("Total");
    model.addColumn("Bayar");
    model.addColumn("Kembali");
    model.addColumn("Tipe");
    model.addColumn("Keterangan");

    tablelog.setModel(model);
}
    

private void loadData() {
    model.setRowCount(0);

    List<modellogt> list = lc.getAll();
    int no = 1;

    for (modellogt lt : list) {
        model.addRow(new Object[]{
            no++,
            lt.getKodeTransaksi(),
            lt.getTanggal(),
            lt.getNamaPelanggan(),
            lt.getTotal(),
            lt.getBayar(),
            lt.getKembali(),
            lt.getTipeTransaksi(),
            lt.getKeterangan()
        });
    }
}

    public void searchtransaksi(String keyword) {
    DefaultTableModel model = (DefaultTableModel) tablelog.getModel();
    model.setRowCount(0);

    String sql = "SELECT * FROM log_transaksi WHERE kode_transaksi LIKE ? OR nama_pelanggan LIKE ?";

    try {
        Connection con = koneksi.getConnection();
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");

        ResultSet rs = ps.executeQuery();

        int no = 1; // Untuk kolom nomor urut di tabel GUI
        while (rs.next()) {
            Object[] row = {
                no++, // Mengisi kolom 'No'
                rs.getString("kode_transaksi"),
                rs.getString("tanggal"),
                rs.getString("nama_pelanggan"),
                rs.getInt("total"),
                rs.getInt("bayar"),
                rs.getInt("kembali"),
                rs.getString("tipe_transaksi"),
                rs.getString("keterangan")
            };
            model.addRow(row);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error search data: " + e.getMessage());
    }
} 

private void bukaDetailTransaksi(String kodeTransaksi) {
    transaksiservice service = new transaksiservice();

    modeltransaksi mt = service.getTransaksiByKode(kodeTransaksi);
    modellogt log = service.getLogByKode(kodeTransaksi); // <-- Ini yang null
    List<modeltd> list = service.getDetailByKode(kodeTransaksi);
    Map<String, modelbarang> mapBarang = service.getBarangByTransaksi(kodeTransaksi);

    // TAMBAHKAN PENGECEKAN INI:
    if (log == null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Data log transaksi tidak ditemukan untuk kode: " + kodeTransaksi, 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return; // Hentikan proses agar tidak error
    }

    // Jika log tidak null, baru jalankan ini
    detailtransaksi form = new detailtransaksi(mt, list, mapBarang, log);
    form.setVisible(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        dashboardbutton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtuser = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        utangbutton1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        utangbutton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dashboardbutton1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dashboardbutton3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelog = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btndetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidepanel.setBackground(new java.awt.Color(23, 118, 211));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardbutton.setBackground(new java.awt.Color(242, 246, 250));
        dashboardbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dashboardbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardbuttonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout dashboardbuttonLayout = new javax.swing.GroupLayout(dashboardbutton);
        dashboardbutton.setLayout(dashboardbuttonLayout);
        dashboardbuttonLayout.setHorizontalGroup(
            dashboardbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardbuttonLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        dashboardbuttonLayout.setVerticalGroup(
            dashboardbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardbuttonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );

        sidepanel.add(dashboardbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 270, 50));

        jPanel6.setBackground(new java.awt.Color(3, 169, 245));

        txtuser.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtuser.setText("User");

        lbl_date.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_date.setText("Tanggal");

        lbl_jam.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_jam.setText("Jam");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtuser)
                    .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtuser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_date)
                .addGap(12, 12, 12)
                .addComponent(lbl_jam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 168, 330, 140));

        utangbutton1.setBackground(new java.awt.Color(242, 246, 250));
        utangbutton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        utangbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utangbutton1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel8.setText("Log Transaksi");
        jLabel8.setAlignmentY(0.0F);

        javax.swing.GroupLayout utangbutton1Layout = new javax.swing.GroupLayout(utangbutton1);
        utangbutton1.setLayout(utangbutton1Layout);
        utangbutton1Layout.setHorizontalGroup(
            utangbutton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utangbutton1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        utangbutton1Layout.setVerticalGroup(
            utangbutton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utangbutton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(utangbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 270, -1));

        utangbutton.setBackground(new java.awt.Color(242, 246, 250));
        utangbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        utangbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utangbuttonMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel4.setText("Utang");
        jLabel4.setAlignmentY(0.0F);

        javax.swing.GroupLayout utangbuttonLayout = new javax.swing.GroupLayout(utangbutton);
        utangbutton.setLayout(utangbuttonLayout);
        utangbuttonLayout.setHorizontalGroup(
            utangbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utangbuttonLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        utangbuttonLayout.setVerticalGroup(
            utangbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utangbuttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(utangbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 270, 50));

        jPanel2.setBackground(new java.awt.Color(242, 246, 250));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Logout_Rounded_Left_20px.png"))); // NOI18N
        jLabel5.setText("LogOut");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 2, Short.MAX_VALUE)))
        );

        sidepanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, 30));

        dashboardbutton1.setBackground(new java.awt.Color(242, 246, 250));
        dashboardbutton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dashboardbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardbutton1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel7.setText("Transaksi");

        javax.swing.GroupLayout dashboardbutton1Layout = new javax.swing.GroupLayout(dashboardbutton1);
        dashboardbutton1.setLayout(dashboardbutton1Layout);
        dashboardbutton1Layout.setHorizontalGroup(
            dashboardbutton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardbutton1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        dashboardbutton1Layout.setVerticalGroup(
            dashboardbutton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardbutton1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(29, 29, 29))
        );

        sidepanel.add(dashboardbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 270, 50));

        dashboardbutton3.setBackground(new java.awt.Color(242, 246, 250));
        dashboardbutton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dashboardbutton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardbutton3MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel9.setText("Stock");

        javax.swing.GroupLayout dashboardbutton3Layout = new javax.swing.GroupLayout(dashboardbutton3);
        dashboardbutton3.setLayout(dashboardbutton3Layout);
        dashboardbutton3Layout.setHorizontalGroup(
            dashboardbutton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardbutton3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        dashboardbutton3Layout.setVerticalGroup(
            dashboardbutton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardbutton3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(29, 29, 29))
        );

        sidepanel.add(dashboardbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 270, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logosmrhitam-removebg-preview 1.png"))); // NOI18N
        sidepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(242, 246, 250));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel1.setText("Log Transaksi");

        tablelog.setBackground(new java.awt.Color(242, 246, 250));
        tablelog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablelog);

        jLabel2.setText("Search :");

        txtsearch.addActionListener(this::txtsearchActionPerformed);
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        btndetail.setText("Detail");
        btndetail.addActionListener(this::btndetailActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(409, 409, 409)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btndetail)))
                        .addGap(0, 433, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndetail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void dashboardbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbuttonMouseClicked
        logtransaksi lt = new logtransaksi();
        lt.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardbuttonMouseClicked

    private void utangbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utangbutton1MouseClicked
        logtransaksi lt = new logtransaksi();
        lt.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_utangbutton1MouseClicked

    private void utangbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utangbuttonMouseClicked
        crudUtang cu = new crudUtang();
        cu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_utangbuttonMouseClicked

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();              // Tutup dashboard
            login lg = new login();      // Kembali ke form login
            lg.setVisible(true);
        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void dashboardbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbutton1MouseClicked
        transaksi tr = new transaksi();
        tr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardbutton1MouseClicked

    private void dashboardbutton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardbutton3MouseClicked
        stock st = new stock();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardbutton3MouseClicked

    private void btndetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetailActionPerformed

    int row = tablelog.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih transaksi terlebih dahulu");
        return;
    }

    String kodeTransaksi = tablelog.getValueAt(row, 1).toString();

    bukaDetailTransaksi(kodeTransaksi);
    }//GEN-LAST:event_btndetailActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
    searchtransaksi(txtsearch.getText());
            if (txtsearch.getText().isEmpty()) {
    loadData();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new logtransaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndetail;
    private javax.swing.JPanel dashboardbutton;
    private javax.swing.JPanel dashboardbutton1;
    private javax.swing.JPanel dashboardbutton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTable tablelog;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JLabel txtuser;
    private javax.swing.JPanel utangbutton;
    private javax.swing.JPanel utangbutton1;
    // End of variables declaration//GEN-END:variables
}
